# This is a basic workflow to help you get started with Actions

name: CI-Java
# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  #job01
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world! 
  
  
  
  depdev:
      runs-on: ubuntu-latest
      environment:
        name: ci-dev
      needs: build
      steps:
        - name: Run a one-line script
          run: deploy Dev
     
     
     
  dephmg:
      runs-on: ubuntu-latest
      environment:
        name: ci-hmg
      needs: depdev
      steps:
        - name: Run a one-line script
          run: deploy HMG
    
    
    
    
  depprd:
      runs-on: ubuntu-latest
      environment:
        name: ci-prod
      needs: dephmg
      steps:
        - name: Run a one-line script
          run: deploy PRD
