# This is a basic workflow to help you get started with Actions

name: CI-Java
# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  #job01
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world! - Build
        
  deploy-dev:
      runs-on: ubuntu-latest
      environment:
        name: ci-dev
        url: teste.com
      needs: build
      steps:
      - name: Run a one-line script
        run: deploy Dev
        
  deploy-hmg:
      runs-on: ubuntu-latest
      environment:
        name: ci-hmg
        url: teste.com
      needs: deploy-dev
      steps:
      - name: Run a one-line script
        run: deploy HMG
        
  deploy-prd:
      runs-on: ubuntu-latest
      environment:
        name: ci-hmg
        url: teste.com
      needs: deploy-hmg
      steps:
      - name: Run a one-line script
        run: deploy PRD
